name = "FACE"
author = "Stefano Zaghi"
copyright  = "Copyright (c) 2016 Stefano Zaghi"
license = "multi-licensing system: GPLv3, BSD2, BSD3, and MIT"
description = "Fortran Ansi Colors (and Styles) Environment"
homepage = "https://github.com/szaghi/FACE"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src/lib"

[install]
library = true
